/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    pages: Page;
    'case-studies': CaseStudy;
    logos: Logo;
    testimonials: Testimonial;
    tags: Tag;
    media: Media;
    settings: Setting;
    navigation: Navigation;
    footer: Footer;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    'case-studies': CaseStudiesSelect<false> | CaseStudiesSelect<true>;
    logos: LogosSelect<false> | LogosSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    tags: TagsSelect<false> | TagsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    settings: SettingsSelect<false> | SettingsSelect<true>;
    navigation: NavigationSelect<false> | NavigationSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * URL path (e.g. "home", "about", "for-investors"). Use "home" for the homepage. Must be unique per site.
   */
  slug: string;
  /**
   * Which sites show this document. Most case studies should be on both.
   */
  brand: ('personal' | 'practice')[];
  status: 'draft' | 'published';
  /**
   * Controls whether this page appears in the main nav.
   */
  nav?: {
    showInNav?: boolean | null;
    /**
     * Override the page title in nav. Leave empty to use title.
     */
    label?: string | null;
    order?: number | null;
  };
  /**
   * Optional. Falls back to the page title and a default OG image.
   */
  seo?: {
    /**
     * Browser tab + search result title.
     */
    title?: string | null;
    /**
     * Meta description for search results.
     */
    description?: string | null;
    /**
     * Open Graph / social share image. 1200×630 recommended.
     */
    ogImage?: (number | null) | Media;
  };
  /**
   * The page builder. Click "+ Add Block" to drop modules onto the page. Drag to reorder.
   */
  blocks?:
    | (
        | {
            eyebrow?: string | null;
            headline: string;
            subhead?: string | null;
            background?: ('none' | 'image' | 'video' | 'animation') | null;
            backgroundMedia?: (number | null) | Media;
            cta?: {
              label?: string | null;
              url?: string | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            eyebrow?: string | null;
            heading?: string | null;
            body?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            width?: ('narrow' | 'wide' | 'full') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textSection';
          }
        | {
            image: number | Media;
            caption?: string | null;
            width?: ('narrow' | 'wide' | 'full') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'image';
          }
        | {
            images?:
              | {
                  image: number | Media;
                  caption?: string | null;
                  id?: string | null;
                }[]
              | null;
            columns?: ('2' | '3' | '4') | null;
            aspectRatio?: ('natural' | 'square' | '4-3' | '16-9' | '3-4') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'imageGrid';
          }
        | {
            size?: ('sm' | 'md' | 'lg' | 'xl') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'spacer';
          }
        | {
            /**
             * Pick 1–3 case studies for the flagship featured block. Order matters.
             */
            caseStudies: (number | CaseStudy)[];
            layout?: ('single' | 'two' | 'three') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'featuredWork';
          }
        | {
            /**
             * Grid of case study tiles. Pick 4–8.
             */
            caseStudies: (number | CaseStudy)[];
            columns?: ('2' | '3') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'caseStudyGrid';
          }
        | {
            /**
             * Pick logos from the Logos collection.
             */
            logos: (number | Logo)[];
            /**
             * Max number to show (logos beyond this are hidden).
             */
            maxCount?: number | null;
            /**
             * Shuffle logo order on each page load.
             */
            randomize?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'logoWall';
          }
        | {
            phase: 'strategy' | 'brand' | 'product' | 'systems' | 'launch';
            title: string;
            description?: string | null;
            /**
             * Logos to show under this lifecycle phase.
             */
            logos?: (number | Logo)[] | null;
            /**
             * Optional small visual artifacts (flow snippets, brand bits, motion stills).
             */
            artifacts?:
              | {
                  image: number | Media;
                  caption?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'lifecycleSection';
          }
        | {
            heading?: string | null;
            items: {
              label: string;
              id?: string | null;
            }[];
            style?: ('inline' | 'pills' | 'grid') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'capabilities';
          }
        | {
            /**
             * Optional section heading.
             */
            heading?: string | null;
            values: {
              title: string;
              description: string;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'values';
          }
        | {
            heading: string;
            body?: string | null;
            ctaLabel: string;
            /**
             * Internal path (/contact) or external URL.
             */
            ctaUrl: string;
            align?: ('center' | 'left') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'cta';
          }
        | {
            image: number | Media;
            alt?: string | null;
            /**
             * Degrees of horizontal skew (e.g. -6).
             */
            skewX?: number | null;
            skewY?: number | null;
            rotate?: number | null;
            rounded?: ('none' | 'sm' | 'md' | 'lg' | 'xl' | 'full') | null;
            shadow?: ('none' | 'soft' | 'dramatic' | 'colored' | 'drop-png') | null;
            /**
             * Hex color, used for "colored" and "drop-png" shadows.
             */
            shadowColor?: string | null;
            shadowBlur?: number | null;
            shadowOffsetX?: number | null;
            shadowOffsetY?: number | null;
            /**
             * Optional. Use a transparent PNG to clip this image (and its shadow) to that silhouette.
             */
            maskImage?: (number | null) | Media;
            hover?: ('none' | 'lift' | 'tilt-3d' | 'parallax-skew') | null;
            /**
             * Max tilt angle in degrees.
             */
            tiltMax?: number | null;
            width?: ('narrow' | 'wide' | 'full') | null;
            caption?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'motionImage';
          }
        | {
            /**
             * Upload a .lottie or .json animation file (e.g. exported from LottieFiles).
             */
            file: number | Media;
            loop?: boolean | null;
            autoplay?: boolean | null;
            /**
             * Only play while the cursor is hovering. Overrides autoplay.
             */
            playOnHover?: boolean | null;
            width?: ('narrow' | 'wide' | 'full') | null;
            caption?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'lottie';
          }
        | {
            /**
             * Logos to scroll. They duplicate seamlessly.
             */
            logos: (number | Logo)[];
            /**
             * Animation duration in seconds. Lower = faster.
             */
            duration?: number | null;
            direction?: ('left' | 'right') | null;
            pauseOnHover?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'marqueeLogos';
          }
        | {
            /**
             * e.g. "April 20, 2022 — April 19 2026"
             */
            dateRange?: string | null;
            lead?: string | null;
            role?: string | null;
            scope?:
              | {
                  label: string;
                  id?: string | null;
                }[]
              | null;
            challengeHeading?: string | null;
            challengeIntro?: string | null;
            architectureIntro?: string | null;
            productSystemIntro?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'baserateCaseStudy';
          }
        | {
            /**
             * e.g. "2020 — 2022"
             */
            dateRange?: string | null;
            lead?: string | null;
            role?: string | null;
            scope?:
              | {
                  label: string;
                  id?: string | null;
                }[]
              | null;
            challengeIntro?: string | null;
            releasesIntro?: string | null;
            outcomesIntro?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'pandaCaseStudy';
          }
        | {
            /**
             * e.g. "2019 — 2022"
             */
            dateRange?: string | null;
            lead?: string | null;
            role?: string | null;
            scope?:
              | {
                  label: string;
                  id?: string | null;
                }[]
              | null;
            challengeIntro?: string | null;
            redesignIntro?: string | null;
            outcomesIntro?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'wingstopCaseStudy';
          }
        | {
            /**
             * e.g. "2013 — 2017"
             */
            dateRange?: string | null;
            lead?: string | null;
            role?: string | null;
            scope?:
              | {
                  label: string;
                  id?: string | null;
                }[]
              | null;
            briefIntro?: string | null;
            workIntro?: string | null;
            outcomesIntro?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'samsungCaseStudy';
          }
        | {
            eyebrow?: string | null;
            /**
             * Page title. Line breaks are preserved.
             */
            heading?: string | null;
            lead?: string | null;
            /**
             * Small print under the lead
             */
            note?: string | null;
            sections?:
              | {
                  /**
                   * Anchor id, e.g. "brand"
                   */
                  id: string;
                  /**
                   * e.g. "03"
                   */
                  num: string;
                  title: string;
                  intro: string;
                  layout?: ('mediaRight' | 'mediaLeft' | 'stack' | 'trio') | null;
                  clients?:
                    | {
                        name: string;
                        id?: string | null;
                      }[]
                    | null;
                  media?:
                    | {
                        label: string;
                        ratio?: ('wide' | 'video' | 'square' | 'portrait' | 'tall') | null;
                        id?: string | null;
                      }[]
                    | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'capabilitiesPage';
          }
        | {
            /**
             * e.g. "01 — Investor Systems". Blank = default.
             */
            kicker?: string | null;
            title?: string | null;
            oneLine?: string | null;
            /**
             * Role · dates line.
             */
            meta?: string | null;
            /**
             * Case study link, e.g. /work/baserate
             */
            href?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'homeFlagshipBaserate';
          }
        | {
            /**
             * e.g. "01 — Investor Systems". Blank = default.
             */
            kicker?: string | null;
            title?: string | null;
            oneLine?: string | null;
            /**
             * Role · dates line.
             */
            meta?: string | null;
            /**
             * Case study link, e.g. /work/baserate
             */
            href?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'homeFlagshipPanda';
          }
        | {
            /**
             * Optional. Default "More work".
             */
            heading?: string | null;
            /**
             * Leave empty to use the default Wingstop / Samsung / Capabilities cards.
             */
            items?:
              | {
                  title?: string | null;
                  blurb?: string | null;
                  meta?: string | null;
                  href?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'homeSecondaryRow';
          }
      )[]
    | null;
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Images, video, and PDFs. Backed by Vercel Blob storage.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Describe the image for accessibility and SEO.
   */
  alt?: string | null;
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    feature?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "case-studies".
 */
export interface CaseStudy {
  id: number;
  title: string;
  /**
   * URL slug (e.g. "panda-express", "baserate"). Unique per site.
   */
  slug: string;
  /**
   * Which sites show this document. Most case studies should be on both.
   */
  brand: ('personal' | 'practice')[];
  status?: ('draft' | 'published') | null;
  /**
   * Show in FeaturedWork blocks.
   */
  featured?: boolean | null;
  /**
   * e.g. "Panda Express", "Baserate"
   */
  client: string;
  /**
   * e.g. "Lead Product Designer", "Art Director"
   */
  role: string;
  dates?: {
    /**
     * e.g. "2022"
     */
    start?: string | null;
    /**
     * e.g. "2024" or "Present"
     */
    end?: string | null;
  };
  /**
   * One sentence describing the outcome. Used in tiles and previews.
   */
  oneLineOutcome: string;
  heroImage?: (number | null) | Media;
  /**
   * Optional looping hero video.
   */
  heroVideo?: (number | null) | Media;
  /**
   * Up to 4 metrics for the case study header.
   */
  metrics?:
    | {
        /**
         * e.g. "4.8★", "+38%"
         */
        value: string;
        /**
         * e.g. "App Store rating"
         */
        label: string;
        /**
         * Optional explanatory text
         */
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  testimonial?: (number | null) | Testimonial;
  tags?: (number | Tag)[] | null;
  /**
   * The case study body. Drop in blocks: TextSection, ImageGrid, Quote, etc.
   */
  blocks?:
    | (
        | {
            eyebrow?: string | null;
            headline: string;
            subhead?: string | null;
            background?: ('none' | 'image' | 'video' | 'animation') | null;
            backgroundMedia?: (number | null) | Media;
            cta?: {
              label?: string | null;
              url?: string | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            eyebrow?: string | null;
            heading?: string | null;
            body?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            width?: ('narrow' | 'wide' | 'full') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textSection';
          }
        | {
            image: number | Media;
            caption?: string | null;
            width?: ('narrow' | 'wide' | 'full') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'image';
          }
        | {
            images?:
              | {
                  image: number | Media;
                  caption?: string | null;
                  id?: string | null;
                }[]
              | null;
            columns?: ('2' | '3' | '4') | null;
            aspectRatio?: ('natural' | 'square' | '4-3' | '16-9' | '3-4') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'imageGrid';
          }
        | {
            size?: ('sm' | 'md' | 'lg' | 'xl') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'spacer';
          }
        | {
            /**
             * Pick 1–3 case studies for the flagship featured block. Order matters.
             */
            caseStudies: (number | CaseStudy)[];
            layout?: ('single' | 'two' | 'three') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'featuredWork';
          }
        | {
            /**
             * Grid of case study tiles. Pick 4–8.
             */
            caseStudies: (number | CaseStudy)[];
            columns?: ('2' | '3') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'caseStudyGrid';
          }
        | {
            /**
             * Pick logos from the Logos collection.
             */
            logos: (number | Logo)[];
            /**
             * Max number to show (logos beyond this are hidden).
             */
            maxCount?: number | null;
            /**
             * Shuffle logo order on each page load.
             */
            randomize?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'logoWall';
          }
        | {
            phase: 'strategy' | 'brand' | 'product' | 'systems' | 'launch';
            title: string;
            description?: string | null;
            /**
             * Logos to show under this lifecycle phase.
             */
            logos?: (number | Logo)[] | null;
            /**
             * Optional small visual artifacts (flow snippets, brand bits, motion stills).
             */
            artifacts?:
              | {
                  image: number | Media;
                  caption?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'lifecycleSection';
          }
        | {
            heading?: string | null;
            items: {
              label: string;
              id?: string | null;
            }[];
            style?: ('inline' | 'pills' | 'grid') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'capabilities';
          }
        | {
            /**
             * Optional section heading.
             */
            heading?: string | null;
            values: {
              title: string;
              description: string;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'values';
          }
        | {
            heading: string;
            body?: string | null;
            ctaLabel: string;
            /**
             * Internal path (/contact) or external URL.
             */
            ctaUrl: string;
            align?: ('center' | 'left') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'cta';
          }
        | {
            image: number | Media;
            alt?: string | null;
            /**
             * Degrees of horizontal skew (e.g. -6).
             */
            skewX?: number | null;
            skewY?: number | null;
            rotate?: number | null;
            rounded?: ('none' | 'sm' | 'md' | 'lg' | 'xl' | 'full') | null;
            shadow?: ('none' | 'soft' | 'dramatic' | 'colored' | 'drop-png') | null;
            /**
             * Hex color, used for "colored" and "drop-png" shadows.
             */
            shadowColor?: string | null;
            shadowBlur?: number | null;
            shadowOffsetX?: number | null;
            shadowOffsetY?: number | null;
            /**
             * Optional. Use a transparent PNG to clip this image (and its shadow) to that silhouette.
             */
            maskImage?: (number | null) | Media;
            hover?: ('none' | 'lift' | 'tilt-3d' | 'parallax-skew') | null;
            /**
             * Max tilt angle in degrees.
             */
            tiltMax?: number | null;
            width?: ('narrow' | 'wide' | 'full') | null;
            caption?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'motionImage';
          }
        | {
            /**
             * Upload a .lottie or .json animation file (e.g. exported from LottieFiles).
             */
            file: number | Media;
            loop?: boolean | null;
            autoplay?: boolean | null;
            /**
             * Only play while the cursor is hovering. Overrides autoplay.
             */
            playOnHover?: boolean | null;
            width?: ('narrow' | 'wide' | 'full') | null;
            caption?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'lottie';
          }
        | {
            /**
             * Logos to scroll. They duplicate seamlessly.
             */
            logos: (number | Logo)[];
            /**
             * Animation duration in seconds. Lower = faster.
             */
            duration?: number | null;
            direction?: ('left' | 'right') | null;
            pauseOnHover?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'marqueeLogos';
          }
        | {
            /**
             * e.g. "April 20, 2022 — April 19 2026"
             */
            dateRange?: string | null;
            lead?: string | null;
            role?: string | null;
            scope?:
              | {
                  label: string;
                  id?: string | null;
                }[]
              | null;
            challengeHeading?: string | null;
            challengeIntro?: string | null;
            architectureIntro?: string | null;
            productSystemIntro?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'baserateCaseStudy';
          }
        | {
            /**
             * e.g. "2020 — 2022"
             */
            dateRange?: string | null;
            lead?: string | null;
            role?: string | null;
            scope?:
              | {
                  label: string;
                  id?: string | null;
                }[]
              | null;
            challengeIntro?: string | null;
            releasesIntro?: string | null;
            outcomesIntro?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'pandaCaseStudy';
          }
        | {
            /**
             * e.g. "2019 — 2022"
             */
            dateRange?: string | null;
            lead?: string | null;
            role?: string | null;
            scope?:
              | {
                  label: string;
                  id?: string | null;
                }[]
              | null;
            challengeIntro?: string | null;
            redesignIntro?: string | null;
            outcomesIntro?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'wingstopCaseStudy';
          }
        | {
            /**
             * e.g. "2013 — 2017"
             */
            dateRange?: string | null;
            lead?: string | null;
            role?: string | null;
            scope?:
              | {
                  label: string;
                  id?: string | null;
                }[]
              | null;
            briefIntro?: string | null;
            workIntro?: string | null;
            outcomesIntro?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'samsungCaseStudy';
          }
        | {
            eyebrow?: string | null;
            /**
             * Page title. Line breaks are preserved.
             */
            heading?: string | null;
            lead?: string | null;
            /**
             * Small print under the lead
             */
            note?: string | null;
            sections?:
              | {
                  /**
                   * Anchor id, e.g. "brand"
                   */
                  id: string;
                  /**
                   * e.g. "03"
                   */
                  num: string;
                  title: string;
                  intro: string;
                  layout?: ('mediaRight' | 'mediaLeft' | 'stack' | 'trio') | null;
                  clients?:
                    | {
                        name: string;
                        id?: string | null;
                      }[]
                    | null;
                  media?:
                    | {
                        label: string;
                        ratio?: ('wide' | 'video' | 'square' | 'portrait' | 'tall') | null;
                        id?: string | null;
                      }[]
                    | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'capabilitiesPage';
          }
        | {
            /**
             * e.g. "01 — Investor Systems". Blank = default.
             */
            kicker?: string | null;
            title?: string | null;
            oneLine?: string | null;
            /**
             * Role · dates line.
             */
            meta?: string | null;
            /**
             * Case study link, e.g. /work/baserate
             */
            href?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'homeFlagshipBaserate';
          }
        | {
            /**
             * e.g. "01 — Investor Systems". Blank = default.
             */
            kicker?: string | null;
            title?: string | null;
            oneLine?: string | null;
            /**
             * Role · dates line.
             */
            meta?: string | null;
            /**
             * Case study link, e.g. /work/baserate
             */
            href?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'homeFlagshipPanda';
          }
        | {
            /**
             * Optional. Default "More work".
             */
            heading?: string | null;
            /**
             * Leave empty to use the default Wingstop / Samsung / Capabilities cards.
             */
            items?:
              | {
                  title?: string | null;
                  blurb?: string | null;
                  meta?: string | null;
                  href?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'homeSecondaryRow';
          }
      )[]
    | null;
  /**
   * Optional. Falls back to the page title and a default OG image.
   */
  seo?: {
    /**
     * Browser tab + search result title.
     */
    title?: string | null;
    /**
     * Meta description for search results.
     */
    description?: string | null;
    /**
     * Open Graph / social share image. 1200×630 recommended.
     */
    ogImage?: (number | null) | Media;
  };
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  name: string;
  /**
   * e.g. "Co-founder, Baserate"
   */
  title?: string | null;
  company?: string | null;
  /**
   * Optional small photo (160×160 minimum).
   */
  headshot?: (number | null) | Media;
  /**
   * 2–3 sentences max. Keep it specific.
   */
  quote: string;
  /**
   * Optionally link to the case study this is about.
   */
  project?: (number | null) | CaseStudy;
  updatedAt: string;
  createdAt: string;
}
/**
 * Tags for filtering case studies (e.g. "Brand", "Product", "Motion").
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags".
 */
export interface Tag {
  id: number;
  name: string;
  /**
   * kebab-case slug for the tag.
   */
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Reusable client/brand logos. Used in LogoWall and LifecycleSection blocks.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "logos".
 */
export interface Logo {
  id: number;
  name: string;
  /**
   * SVG preferred. Falls back to PNG.
   */
  image: number | Media;
  /**
   * Optional dark-theme variant.
   */
  imageDark?: (number | null) | Media;
  /**
   * Optional URL the logo links to.
   */
  link?: string | null;
  industry?: ('consumer' | 'fintech' | 'enterprise' | 'b2b' | 'agency' | 'startup') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Per-brand site settings. Create one entry for "personal" and one for "practice".
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings".
 */
export interface Setting {
  id: number;
  brand: 'personal' | 'practice';
  siteName: string;
  tagline?: string | null;
  /**
   * Default social share image.
   */
  defaultOGImage?: (number | null) | Media;
  contactEmail: string;
  /**
   * Cal.com / Calendly URL.
   */
  calLink?: string | null;
  socialLinks?:
    | {
        platform?: ('linkedin' | 'instagram' | 'x' | 'dribbble' | 'readcv' | 'github') | null;
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Small copyright/footer line.
   */
  footerCopy?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Top-level nav. One entry per brand.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: number;
  brand: 'personal' | 'practice';
  items?:
    | {
        label: string;
        type?: ('page' | 'external') | null;
        page?: (number | null) | Page;
        externalUrl?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Footer content. One entry per brand.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  brand: 'personal' | 'practice';
  columns?:
    | {
        heading?: string | null;
        items?:
          | {
              label: string;
              url: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * e.g. "© 2026 Joshua Schaeffer."
   */
  copyrightText?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'case-studies';
        value: number | CaseStudy;
      } | null)
    | ({
        relationTo: 'logos';
        value: number | Logo;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'tags';
        value: number | Tag;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'settings';
        value: number | Setting;
      } | null)
    | ({
        relationTo: 'navigation';
        value: number | Navigation;
      } | null)
    | ({
        relationTo: 'footer';
        value: number | Footer;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  brand?: T;
  status?: T;
  nav?:
    | T
    | {
        showInNav?: T;
        label?: T;
        order?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        ogImage?: T;
      };
  blocks?:
    | T
    | {
        hero?:
          | T
          | {
              eyebrow?: T;
              headline?: T;
              subhead?: T;
              background?: T;
              backgroundMedia?: T;
              cta?:
                | T
                | {
                    label?: T;
                    url?: T;
                  };
              id?: T;
              blockName?: T;
            };
        textSection?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              body?: T;
              width?: T;
              id?: T;
              blockName?: T;
            };
        image?:
          | T
          | {
              image?: T;
              caption?: T;
              width?: T;
              id?: T;
              blockName?: T;
            };
        imageGrid?:
          | T
          | {
              images?:
                | T
                | {
                    image?: T;
                    caption?: T;
                    id?: T;
                  };
              columns?: T;
              aspectRatio?: T;
              id?: T;
              blockName?: T;
            };
        spacer?:
          | T
          | {
              size?: T;
              id?: T;
              blockName?: T;
            };
        featuredWork?:
          | T
          | {
              caseStudies?: T;
              layout?: T;
              id?: T;
              blockName?: T;
            };
        caseStudyGrid?:
          | T
          | {
              caseStudies?: T;
              columns?: T;
              id?: T;
              blockName?: T;
            };
        logoWall?:
          | T
          | {
              logos?: T;
              maxCount?: T;
              randomize?: T;
              id?: T;
              blockName?: T;
            };
        lifecycleSection?:
          | T
          | {
              phase?: T;
              title?: T;
              description?: T;
              logos?: T;
              artifacts?:
                | T
                | {
                    image?: T;
                    caption?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        capabilities?:
          | T
          | {
              heading?: T;
              items?:
                | T
                | {
                    label?: T;
                    id?: T;
                  };
              style?: T;
              id?: T;
              blockName?: T;
            };
        values?:
          | T
          | {
              heading?: T;
              values?:
                | T
                | {
                    title?: T;
                    description?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        cta?:
          | T
          | {
              heading?: T;
              body?: T;
              ctaLabel?: T;
              ctaUrl?: T;
              align?: T;
              id?: T;
              blockName?: T;
            };
        motionImage?:
          | T
          | {
              image?: T;
              alt?: T;
              skewX?: T;
              skewY?: T;
              rotate?: T;
              rounded?: T;
              shadow?: T;
              shadowColor?: T;
              shadowBlur?: T;
              shadowOffsetX?: T;
              shadowOffsetY?: T;
              maskImage?: T;
              hover?: T;
              tiltMax?: T;
              width?: T;
              caption?: T;
              id?: T;
              blockName?: T;
            };
        lottie?:
          | T
          | {
              file?: T;
              loop?: T;
              autoplay?: T;
              playOnHover?: T;
              width?: T;
              caption?: T;
              id?: T;
              blockName?: T;
            };
        marqueeLogos?:
          | T
          | {
              logos?: T;
              duration?: T;
              direction?: T;
              pauseOnHover?: T;
              id?: T;
              blockName?: T;
            };
        baserateCaseStudy?:
          | T
          | {
              dateRange?: T;
              lead?: T;
              role?: T;
              scope?:
                | T
                | {
                    label?: T;
                    id?: T;
                  };
              challengeHeading?: T;
              challengeIntro?: T;
              architectureIntro?: T;
              productSystemIntro?: T;
              id?: T;
              blockName?: T;
            };
        pandaCaseStudy?:
          | T
          | {
              dateRange?: T;
              lead?: T;
              role?: T;
              scope?:
                | T
                | {
                    label?: T;
                    id?: T;
                  };
              challengeIntro?: T;
              releasesIntro?: T;
              outcomesIntro?: T;
              id?: T;
              blockName?: T;
            };
        wingstopCaseStudy?:
          | T
          | {
              dateRange?: T;
              lead?: T;
              role?: T;
              scope?:
                | T
                | {
                    label?: T;
                    id?: T;
                  };
              challengeIntro?: T;
              redesignIntro?: T;
              outcomesIntro?: T;
              id?: T;
              blockName?: T;
            };
        samsungCaseStudy?:
          | T
          | {
              dateRange?: T;
              lead?: T;
              role?: T;
              scope?:
                | T
                | {
                    label?: T;
                    id?: T;
                  };
              briefIntro?: T;
              workIntro?: T;
              outcomesIntro?: T;
              id?: T;
              blockName?: T;
            };
        capabilitiesPage?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              lead?: T;
              note?: T;
              sections?:
                | T
                | {
                    id?: T;
                    num?: T;
                    title?: T;
                    intro?: T;
                    layout?: T;
                    clients?:
                      | T
                      | {
                          name?: T;
                          id?: T;
                        };
                    media?:
                      | T
                      | {
                          label?: T;
                          ratio?: T;
                          id?: T;
                        };
                  };
              id?: T;
              blockName?: T;
            };
        homeFlagshipBaserate?:
          | T
          | {
              kicker?: T;
              title?: T;
              oneLine?: T;
              meta?: T;
              href?: T;
              id?: T;
              blockName?: T;
            };
        homeFlagshipPanda?:
          | T
          | {
              kicker?: T;
              title?: T;
              oneLine?: T;
              meta?: T;
              href?: T;
              id?: T;
              blockName?: T;
            };
        homeSecondaryRow?:
          | T
          | {
              heading?: T;
              items?:
                | T
                | {
                    title?: T;
                    blurb?: T;
                    meta?: T;
                    href?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "case-studies_select".
 */
export interface CaseStudiesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  brand?: T;
  status?: T;
  featured?: T;
  client?: T;
  role?: T;
  dates?:
    | T
    | {
        start?: T;
        end?: T;
      };
  oneLineOutcome?: T;
  heroImage?: T;
  heroVideo?: T;
  metrics?:
    | T
    | {
        value?: T;
        label?: T;
        description?: T;
        id?: T;
      };
  testimonial?: T;
  tags?: T;
  blocks?:
    | T
    | {
        hero?:
          | T
          | {
              eyebrow?: T;
              headline?: T;
              subhead?: T;
              background?: T;
              backgroundMedia?: T;
              cta?:
                | T
                | {
                    label?: T;
                    url?: T;
                  };
              id?: T;
              blockName?: T;
            };
        textSection?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              body?: T;
              width?: T;
              id?: T;
              blockName?: T;
            };
        image?:
          | T
          | {
              image?: T;
              caption?: T;
              width?: T;
              id?: T;
              blockName?: T;
            };
        imageGrid?:
          | T
          | {
              images?:
                | T
                | {
                    image?: T;
                    caption?: T;
                    id?: T;
                  };
              columns?: T;
              aspectRatio?: T;
              id?: T;
              blockName?: T;
            };
        spacer?:
          | T
          | {
              size?: T;
              id?: T;
              blockName?: T;
            };
        featuredWork?:
          | T
          | {
              caseStudies?: T;
              layout?: T;
              id?: T;
              blockName?: T;
            };
        caseStudyGrid?:
          | T
          | {
              caseStudies?: T;
              columns?: T;
              id?: T;
              blockName?: T;
            };
        logoWall?:
          | T
          | {
              logos?: T;
              maxCount?: T;
              randomize?: T;
              id?: T;
              blockName?: T;
            };
        lifecycleSection?:
          | T
          | {
              phase?: T;
              title?: T;
              description?: T;
              logos?: T;
              artifacts?:
                | T
                | {
                    image?: T;
                    caption?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        capabilities?:
          | T
          | {
              heading?: T;
              items?:
                | T
                | {
                    label?: T;
                    id?: T;
                  };
              style?: T;
              id?: T;
              blockName?: T;
            };
        values?:
          | T
          | {
              heading?: T;
              values?:
                | T
                | {
                    title?: T;
                    description?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        cta?:
          | T
          | {
              heading?: T;
              body?: T;
              ctaLabel?: T;
              ctaUrl?: T;
              align?: T;
              id?: T;
              blockName?: T;
            };
        motionImage?:
          | T
          | {
              image?: T;
              alt?: T;
              skewX?: T;
              skewY?: T;
              rotate?: T;
              rounded?: T;
              shadow?: T;
              shadowColor?: T;
              shadowBlur?: T;
              shadowOffsetX?: T;
              shadowOffsetY?: T;
              maskImage?: T;
              hover?: T;
              tiltMax?: T;
              width?: T;
              caption?: T;
              id?: T;
              blockName?: T;
            };
        lottie?:
          | T
          | {
              file?: T;
              loop?: T;
              autoplay?: T;
              playOnHover?: T;
              width?: T;
              caption?: T;
              id?: T;
              blockName?: T;
            };
        marqueeLogos?:
          | T
          | {
              logos?: T;
              duration?: T;
              direction?: T;
              pauseOnHover?: T;
              id?: T;
              blockName?: T;
            };
        baserateCaseStudy?:
          | T
          | {
              dateRange?: T;
              lead?: T;
              role?: T;
              scope?:
                | T
                | {
                    label?: T;
                    id?: T;
                  };
              challengeHeading?: T;
              challengeIntro?: T;
              architectureIntro?: T;
              productSystemIntro?: T;
              id?: T;
              blockName?: T;
            };
        pandaCaseStudy?:
          | T
          | {
              dateRange?: T;
              lead?: T;
              role?: T;
              scope?:
                | T
                | {
                    label?: T;
                    id?: T;
                  };
              challengeIntro?: T;
              releasesIntro?: T;
              outcomesIntro?: T;
              id?: T;
              blockName?: T;
            };
        wingstopCaseStudy?:
          | T
          | {
              dateRange?: T;
              lead?: T;
              role?: T;
              scope?:
                | T
                | {
                    label?: T;
                    id?: T;
                  };
              challengeIntro?: T;
              redesignIntro?: T;
              outcomesIntro?: T;
              id?: T;
              blockName?: T;
            };
        samsungCaseStudy?:
          | T
          | {
              dateRange?: T;
              lead?: T;
              role?: T;
              scope?:
                | T
                | {
                    label?: T;
                    id?: T;
                  };
              briefIntro?: T;
              workIntro?: T;
              outcomesIntro?: T;
              id?: T;
              blockName?: T;
            };
        capabilitiesPage?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              lead?: T;
              note?: T;
              sections?:
                | T
                | {
                    id?: T;
                    num?: T;
                    title?: T;
                    intro?: T;
                    layout?: T;
                    clients?:
                      | T
                      | {
                          name?: T;
                          id?: T;
                        };
                    media?:
                      | T
                      | {
                          label?: T;
                          ratio?: T;
                          id?: T;
                        };
                  };
              id?: T;
              blockName?: T;
            };
        homeFlagshipBaserate?:
          | T
          | {
              kicker?: T;
              title?: T;
              oneLine?: T;
              meta?: T;
              href?: T;
              id?: T;
              blockName?: T;
            };
        homeFlagshipPanda?:
          | T
          | {
              kicker?: T;
              title?: T;
              oneLine?: T;
              meta?: T;
              href?: T;
              id?: T;
              blockName?: T;
            };
        homeSecondaryRow?:
          | T
          | {
              heading?: T;
              items?:
                | T
                | {
                    title?: T;
                    blurb?: T;
                    meta?: T;
                    href?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        ogImage?: T;
      };
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "logos_select".
 */
export interface LogosSelect<T extends boolean = true> {
  name?: T;
  image?: T;
  imageDark?: T;
  link?: T;
  industry?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  name?: T;
  title?: T;
  company?: T;
  headshot?: T;
  quote?: T;
  project?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags_select".
 */
export interface TagsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        feature?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings_select".
 */
export interface SettingsSelect<T extends boolean = true> {
  brand?: T;
  siteName?: T;
  tagline?: T;
  defaultOGImage?: T;
  contactEmail?: T;
  calLink?: T;
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  footerCopy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  brand?: T;
  items?:
    | T
    | {
        label?: T;
        type?: T;
        page?: T;
        externalUrl?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  brand?: T;
  columns?:
    | T
    | {
        heading?: T;
        items?:
          | T
          | {
              label?: T;
              url?: T;
              id?: T;
            };
        id?: T;
      };
  copyrightText?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}