/**
 * Panda Express case study — content defaults.
 * Same pattern as the Baserate build: all copy lives here; the Payload block
 * only carries optional overrides. Outcomes stats are sourced from public
 * reporting (verified June 2026):
 *  - Apple App Store listing (4.8★, 574K ratings)
 *  - WWT × Panda Express case study (16M+ members, $1B+ member sales, Ipsos #1)
 *  - Nation's Restaurant News, June 2023 (delivery 3×+ since Panda Delivers, 2020)
 *  - Google Play listing (5M+ installs)
 */

export const overview = {
  client: 'Panda Express',
  dateRange: '2020 — 2022',
  lead: 'Panda Express needed its digital ordering rebuilt for a world that suddenly couldn’t walk up to the counter. I led design on the mobile app through two releases — a COVID sprint shipped under extreme pressure, then the full experience with a rewards program — plus the marketing site that wrapped around it.',
  role: 'Lead Designer & Art Director (Hathway, now Bounteous) — managed a small design team, personally designed nearly all of the app’s UI/UX, built the working prototypes, and ran the 6-hour stakeholder presentations that carried the vision through.',
  scope: [
    'Mobile App UI/UX',
    'Art Direction',
    'Team Leadership',
    'Prototyping',
    'Rewards Program',
    'Marketing Site',
  ],
}

export const challenge = {
  heading: 'THE CHALLENGE',
  intro: 'An order placed on a phone has to be true in three places at once: the platform that takes it, the restaurant that cooks it, and the guest standing outside waiting on it. Most of the hard design work lived in that pipeline — making backend data, store operations, and the guest experience agree with each other in real time.',
  problems: [
    {
      tag: '01',
      title: 'One order, three systems',
      body: 'Menus, pricing, item availability, and order status originated in the backend, were acted on in the restaurant, and were promised to the guest. Every screen had to be designed around what each system actually knew — and when it knew it.',
    },
    {
      tag: '02',
      title: '2,300+ restaurants, each their own source of truth',
      body: 'Store hours, regional menus, sold-out items, kitchen throughput at peak. The UI had to absorb per-location variance without ever making the guest do the reconciling.',
    },
    {
      tag: '03',
      title: 'Zero margin for confusion',
      body: 'COVID made the order pipeline the business. Contactless pickup and delivery only work when the status a guest sees matches what the kitchen is doing — designing that trust was the job.',
    },
  ],
}

export const releases = {
  heading: 'THE TWO RELEASES',
  intro: 'The product shipped twice: first as an emergency, then as a vision. Same team, two completely different definitions of done.',
  phases: [
    {
      tag: 'PHASE 01 · 2020',
      title: 'The COVID sprint',
      body: 'When dining rooms closed, digital ordering went from a convenience to the only way to serve guests. We compressed the roadmap into a rushed release: core ordering, pickup, and delivery flows designed and shipped in weeks, prioritizing the essential path over polish.',
      placeholder: 'V1 app screens — in progress',
    },
    {
      tag: 'PHASE 02 · 2021–2022',
      title: 'The full experience + rewards',
      body: 'With the fires out, we rebuilt it the way it was always meant to be: the complete ordering experience, a ground-up rewards program woven through every flow, and working prototypes that anchored 6-hour stakeholder presentations.',
      placeholder: 'V2 app + rewards screens — in progress',
    },
  ],
  alsoShipped: 'Also shipped — the PandaExpress.com marketing site: brand storytelling and online ordering unified into one seamless experience.',
}

export interface PandaStat {
  /** numeric target the count-up animates to */
  value: number
  /** decimal places to render during/after the count-up (default 0) */
  decimals?: number
  prefix?: string
  /** rendered in Panda red after the number, e.g. "M+" / "★" */
  suffix?: string
  label: string
  description: string
}

export const outcomes = {
  heading: 'OUTCOMES',
  lead: 'A platform born in a crisis became the backbone of Panda’s digital business. The app, the rewards program, and the site now carry a measurable share of one of America’s largest restaurant brands.',
  stats: [
    {
      value: 4.8,
      decimals: 1,
      suffix: '★',
      label: 'App Store Rating',
      description: 'Across 574,000+ ratings on iOS — sustained while the app scaled to millions of guests.',
    },
    {
      value: 16,
      suffix: 'M+',
      label: 'Rewards Members',
      description: 'Panda Rewards members since the program launched on the platform.',
    },
    {
      value: 1,
      prefix: '$',
      suffix: 'B+',
      label: 'Member Sales',
      description: 'In sales generated by Panda Rewards members through the digital experience.',
    },
    {
      value: 1,
      prefix: '#',
      label: 'Digital Ordering, US',
      description: 'Ranked first of 26 brands in Ipsos’ 2024 Digital Ordering Performance study — highest score overall and for app benefits.',
    },
    {
      value: 3,
      suffix: '×',
      label: 'Delivery Growth',
      description: 'Delivery business more than tripled after Panda Delivers launched through the app and site in 2020.',
    },
    {
      value: 5,
      suffix: 'M+',
      label: 'Android Installs',
      description: 'Google Play downloads, alongside the iOS install base that anchors the rating above.',
    },
  ] as PandaStat[],
  sources:
    'Sources: Apple App Store (2026) · WWT × Panda Express case study · Ipsos QSR Digital Ordering Performance Study, 2024 · Nation’s Restaurant News · Google Play (2026)',
}
