/**
 * Panda Express case study — content defaults.
 * Same pattern as the Baserate build: all copy lives here; the Payload block
 * only carries optional overrides. Outcomes stats are sourced from public
 * reporting (verified June 2026):
 *  - Apple App Store listing (4.8★, 574K ratings)
 *  - WWT × Panda Express case study (16M+ members, $1B+ member sales, Ipsos #1)
 *  - Nation's Restaurant News, June 2023 (delivery 3×+ since Panda Delivers, 2020)
 *  - Google Play listing (5M+ installs)
 */

export const overview = {
  client: 'Panda Express',
  dateRange: 'November 2019 — April 2022',
  lead: 'Working for Hathway from pitch to launch for 2 versions of the Panda Express App and marketing site.',
  role: 'Art Director + Product Lead',
  scope: [
    'Project Pitch',
    'Product Strategy',
    'Product UX',
    'Product UI',
    'Marketing UI + UX',
    'Presentations',
  ],
}

export const challenge = {
  heading: 'THE CHALLENGE',
  intro: 'An order placed on a phone has to be true in three places at once: the platform that takes it, the restaurant that cooks it, and the guest standing outside waiting on it. Most of the hard design work lived in that pipeline — making backend data, store operations, and the guest experience agree with each other in real time.',
  problems: [
    {
      tag: '01',
      title: 'One order, three systems',
      body: 'Menus, pricing, item availability, and order status originated in the backend, were acted on in the restaurant, and were promised to the guest. Every screen had to be designed around what each system actually knew — and when it knew it.',
    },
    {
      tag: '02',
      title: '2,300+ restaurants, each their own source of truth',
      body: 'Store hours, regional menus, sold-out items, kitchen throughput at peak. The UI had to absorb per-location variance without ever making the guest do the reconciling.',
    },
    {
      tag: '03',
      title: 'Zero margin for confusion',
      body: 'COVID made the order pipeline the business. Contactless pickup and delivery only work when the status a guest sees matches what the kitchen is doing — designing that trust was the job.',
    },
  ],
}

export const releases = {
  heading: '2020 PIVOT',
  intro:
    '2020 required a massive product pivot. Three months into UX discovery, mobile ordering became incredibly important. The new plan: a quick, minimal app in three months, followed by a full rewards app the following year.',
  phasesLabel: '2 PHASES',
  phasesIntro: 'Added brand differentiation to emphasize the value gain from the free to paid product.',
  mvp: {
    title: 'MVP FAST-LAUNCH',
    body: 'The fast launch emphasized core ordering and prioritized the web experience.',
  },
  /** Device-scatter band that follows the 2-card grid (Figma "MVP Section 3"). */
  scatter: {
    title: 'Seamless Simple Reordering',
    body: 'Designed every page to factor in the unique ordering style of Panda Express.',
  },
  rewards: {
    title: 'FULL REWARDS APP',
    body: 'The full set of features, a better native app experience, and the rewards functionality was added as a follow-up to the core app.',
  },
}

export interface PandaStat {
  /** numeric target the count-up animates to */
  value: number
  /** decimal places to render during/after the count-up (default 0) */
  decimals?: number
  prefix?: string
  /** rendered in Panda red after the number, e.g. "M+" / "★" */
  suffix?: string
  label: string
  description: string
}

export const outcomes = {
  heading: 'OUTCOMES',
  lead: 'A platform born in a crisis became the backbone of Panda’s digital business. The app, the rewards program, and the site now carry a measurable share of one of America’s largest restaurant brands.',
  stats: [
    {
      value: 4.8,
      decimals: 1,
      suffix: '★',
      label: 'App Store Rating',
      description: 'Across 574,000+ ratings on iOS — sustained while the app scaled to millions of guests.',
    },
    {
      value: 16,
      suffix: 'M+',
      label: 'Rewards Members',
      description: 'Panda Rewards members since the program launched on the platform.',
    },
    {
      value: 1,
      prefix: '$',
      suffix: 'B+',
      label: 'Member Sales',
      description: 'In sales generated by Panda Rewards members through the digital experience.',
    },
    {
      value: 1,
      prefix: '#',
      label: 'Digital Ordering, US',
      description: 'Ranked first of 26 brands in Ipsos’ 2024 Digital Ordering Performance study — highest score overall and for app benefits.',
    },
    {
      value: 3,
      suffix: '×',
      label: 'Delivery Growth',
      description: 'Delivery business more than tripled after Panda Delivers launched through the app and site in 2020.',
    },
    {
      value: 5,
      suffix: 'M+',
      label: 'Android Installs',
      description: 'Google Play downloads, alongside the iOS install base that anchors the rating above.',
    },
  ] as PandaStat[],
  sources:
    'Sources: Apple App Store (2026) · WWT × Panda Express case study · Ipsos QSR Digital Ordering Performance Study, 2024 · Nation’s Restaurant News · Google Play (2026)',
}

/**
 * Component Libraries — second item inside the MVP Fast-Launch section.
 * Copy mirrors the Figma frame header (node 263:46908). Two flat artifact
 * sheets live in /public/panda/components/.
 */
export const componentLibraries = {
  title: 'COMPONENT LIBRARIES',
  body: 'Component libraries included everything from icons to larger, complex components, along with a consistent set of illustrative iconography.',
}
